### ISSUE TITLE
Building Ios in release mode. Xcode 9.3 - MTouch error

### ISSUE THREAD

**Issue by andyduong** [CrossGeeks/FacebookClientPlugin#17]
If you are creating an issue for a BUG please fill out this information. If you are asking a question or requesting a feature you can delete the sections below. 

**Failure to fill out this information will result in this issue being closed.** If you post a full stack trace in a bug it will be closed, please post it to http://gist.github.com and then post the link here.

## Bug Information

Version Number of Plugin: 1.2.0
Device Tested On: Iphone 6 ios11.3
Simulator Tested On: Iphone X ios 11.3
Version of VS:  Visual Studio Mac 7.5
Version of Xamarin: Xamarin Mono 5.8.1
Versions of other things you are using:

### Steps to reproduce the Behavior
Building for App store for XCode 9.3 

### Expected Behavior
It will build without the plugin. 

### Actual Behavior
Error:
/Users/andyduong/Documents/dev/SpreadSlayerMobile/iOS/MTOUCH: Error MT2101: Can't resolve the reference 'System.Void Facebook.ShareKit.SharingContent_Extensions::SetHashtag(Facebook.ShareKit.ISharingContent,Facebook.ShareKit.Hashtag)', referenced from the method 'System.Void Plugin.FacebookClient.FacebookClientManager::RequestShare(System.Collections.Generic.Dictionary`2<System.String,System.Object>)' in 'Facebook, Version=4.10.0.0, Culture=neutral, PublicKeyToken=null'. (MT2101) (SpreadSlayer.iOS)

**Comment by rdelrosario** [comment]
Did you try building the sample?

**Comment by rdelrosario** [comment]
What is your Android compilation target?

**Comment by herychemo** [comment]
any update for this? 
i can just build my iOS project when the target is the iOS simulator, otherwise i get error 

**/Volumes/DATA/Projects/GitHub/localslash-app/LocalSlash_iOS/MTOUCH: Error MT2101: Can't resolve the reference 'System.Void Facebook.ShareKit.SharingContent_Extensions::SetHashtag(Facebook.ShareKit.ISharingContent,Facebook.ShareKit.Hashtag)', referenced from the method 'System.Void Plugin.FacebookClient.FacebookClientManager::RequestShare(System.Collections.Generic.Dictionary`2<System.String,System.Object>)' in 'Facebook, Version=4.10.0.0, Culture=neutral, PublicKeyToken=null'. (MT2101) (LocalSlash_iOS)**

please help

**Comment by bda2206** [comment]
Getting the same error

Version Number of Plugin: 1.2.0
Device Tested On: Iphone 6 ios11.4
Simulator Tested On: n/a
Version of VS: Visual Studio 17
Version of Xamarin: Xamarin Forms 3.1.0.583944
Xamarin.Facebook.IOS v4.33
Versions of other things you are using:

Steps to reproduce the Behavior
Building for debug on Iphone Xcode is 9.4.1

Expected Behavior
It will build 

Actual Behavior
Error:
Severity	Code	Description	Project	File	Line	Suppression State
Error		Can't resolve the reference 'System.Void Facebook.ShareKit.SharingContent_Extensions::SetHashtag(Facebook.ShareKit.ISharingContent,Facebook.ShareKit.Hashtag)', referenced from the method 'System.Void Plugin.FacebookClient.FacebookClientManager::RequestShare(System.Collections.Generic.Dictionary`2<System.String,System.Object>)' in 'Facebook, Version=4.10.0.0, Culture=neutral, PublicKeyToken=null'.	acrossWords.iOS

**Comment by bda2206** [comment]
@Xtergs thanks, yours compiles 👍

**Comment by rdelrosario** [comment]
@xtergs Thanks for your PR, just updated the NuGet package:

https://www.nuget.org/packages/Plugin.FacebookClient/1.3.0
